import { Xanh_Mono, Doto, Space_Grotesk } from "next/font/google";
import "@/styles/globals.css";

const xanhMono = Xanh_Mono({
    variable: "--font-serif",
    weight: ["400"],

});

const doto = Doto({
    variable: "--font-accent",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const spaceGrotesk = Space_Grotesk({
    variable: "--font-mono",
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${xanhMono.variable} ${doto.variable} ${spaceGrotesk.variable} antialiased`}>{children}</body>
        </html>
    );
}
