import { Xanh_Mono, Doto, Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";
import '@/styles/globals.css';   

const xanhMono = Xanh_Mono({
    variable: "--font-serif",
    weight: ["400"],
    subsets: ["latin"],
});

const doto = Doto({
    variable: "--font-accent",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const spaceGrotesk = Space_Grotesk({
    variable: "--font-mono",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="light">
            <body className={`${xanhMono.variable} ${doto.variable} ${spaceGrotesk.variable} antialiased bg-chBgPrimary`}>
                <ThemeProvider>{children}</ThemeProvider>
            </body>
        </html>
    );
}
